### ISSUE TITLE
got SIGSEGV using in Spark

### ISSUE THREAD

**Issue by AzatFazulzyanov** [alexandrnikitin/bloom-filter-scala#16]
I tried to use your implementation in Spark and got that 
>
> A fatal error has been detected by the Java Runtime Environment:
>
>  SIGSEGV (0xb) at pc=0x000000010d75d414, pid=34100, tid=48387
>
> JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
> Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode bsd-amd64 compressed oops)
> Problematic frame:
> V  [libjvm.dylib+0x55d414]
>
> Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
>
> An error report file with more information is saved as:
> hs_err_pid34100.log
> Compiled method (nm)   10145 2030     n 0       sun.misc.Unsafe::getObject (native)
>  total in heap  [0x000000010e7b98d0,0x000000010e7b9c28] = 856
>  relocation     [0x000000010e7b99f8,0x000000010e7b9a38] = 64
>  main code      [0x000000010e7b9a40,0x000000010e7b9c28] = 488
> Compiled method (nm)   10145 2030     n 0       sun.misc.Unsafe::getObject (native)
> total in heap  [0x000000010e7b98d0,0x000000010e7b9c28] = 856
> relocation     [0x000000010e7b99f8,0x000000010e7b9a38] = 64
> main code      [0x000000010e7b9a40,0x000000010e7b9c28] = 488
>
> If you would like to submit a bug report, please visit:
>   http://bugreport.java.com/bugreport/crash.jsp

 #

[hs_err_pid34100.txt](https://github.com/alexandrnikitin/bloom-filter-scala/files/580155/hs_err_pid34100.txt)

**Comment by alexandrnikitin** [comment]
@AzatFazulzyanov Thank you for the report. Could you share more details please. Which version do you use? How do you create and use Bloom filter in Spark. I would appreciate a small repro. 
_Please be aware that capturing or broadcasting the variable won't work because the BF class doesn't "contain" the memory but a pointer to it. You need to use serialization/deserialization instead._

**Comment by AzatFazulzyanov** [comment]
Oh, I tried to simply broadcast it, so it would not work, that is the point.

**Comment by alexandrnikitin** [comment]
The BF class exposes `def writeTo(out: OutputStream)` and `def readFrom[T](in: InputStream)` APIs for serialization and deserialization respectively. Try to use them please.
