### ISSUE TITLE
Scala 2.10 support

### ISSUE THREAD

**Issue by alexandrnikitin** [alexandrnikitin/bloom-filter-scala#2]
nice to have: 2.12 and `dotty`

**Comment by xyangk** [comment]
I can only find [2.11](http://mvnrepository.com/artifact/com.github.alexandrnikitin) `libraryDependencies += "com.github.alexandrnikitin" % "bloom-filter_2.11" % "0.5.0"` , but I need 2.10 version, where can I find it ?

**Comment by alexandrnikitin** [comment]
I pushed `0.6.0` with Scala 2.10 support to Sonatype: https://oss.sonatype.org/#nexus-search;quick~bloom-filter-2.10 This release will be synced with Maven soon.
Something like `libraryDependencies += "com.github.alexandrnikitin" % "bloom-filter_2.10" % "0.6.0"` with the sonatype resolver should work.
