### ISSUE TITLE
Scala 2.12.1 support?

### ISSUE THREAD

**Issue by dmrolfs** [alexandrnikitin/bloom-filter-scala#22]
With 2.12 scala.concurrent.util.Unsafe is removed impacting this project. Are you planning to update accordingly?  I'm curious about your thoughts on how to go about it. Thanks

**Comment by dmrolfs** [comment]
I'm happy to help, and would appreciate any guidance in what you think may be promising.

**Comment by alexandrnikitin** [comment]
@dmrolfs Thanks for the issue. Scala 2.12.x support is definitely needed! Frankly I didn't investigate the topic yet to propose anything.

**Comment by fediq** [comment]
@alexandrnikitin I've added Scala 2.12 support in #31 . Could you review it please?

**Comment by alexandrnikitin** [comment]
@fediq Thank you for your time!

I published `v0.10.0` with Scala 2.12 support

**Comment by alexandrnikitin** [comment]
Closed via #31
