### ISSUE TITLE
Union two Bloom Filters

### ISSUE THREAD

**Issue by upio** [alexandrnikitin/bloom-filter-scala#4]
Add support for computing bloom filters in a distributed fashion by generating and OR'ing multiple bloom filters in to one.

Breeze is a good reference point for this issue: https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/util/BloomFilter.scala#L84

**Comment by jarandaf** [comment]
Bloom filters are actually monoids. Some starting point: https://github.com/twitter/algebird/blob/7bcbc68776b7ecc01cc005a223755a7722c6f6dd/algebird-core/src/main/scala/com/twitter/algebird/BloomFilter.scala

**Comment by alexandrnikitin** [comment]
Pushed 0.5.0 with union support.
