### ISSUE TITLE
Serialization Support

### ISSUE THREAD

**Issue by upio** [alexandrnikitin/bloom-filter-scala#5]
Add support for Java and Kryo serialization so that the Bloom Filter can be used in distributed applications such as Apache Spark.

**Comment by kutchar** [comment]
Can this be done by serializing the [UnsafeBitArray](https://github.com/alexandrnikitin/bloom-filter-scala/blob/master/bloom-filter/src/main/scala/bloomfilter/mutable/UnsafeBitArray.scala)?

**Comment by velvia** [comment]
I'd like to propose a PR to create a byte array by copying the UnsafeBitArray along with the parameters needed for reconstructing the BloomFilter instance.  From there simple wrappers can be created for any other serialization scheme, but those of us who want to write these into storage or without specific serialization can easily do so.

**Comment by alexandrnikitin** [comment]
@velvia Great! You are welcome to do it! I don't have strong vision about the best way to do it. Should we bring Kryo dependency in? Would the raw bytes be enough to cover all use cases? BTW, There's one PR already with some work https://github.com/alexandrnikitin/bloom-filter-scala/pull/10/files

**Comment by velvia** [comment]
@alexandrnikitin actually the serialization in the other PR is adequate for my needs, I suggest we just start with that.

I strongly recommend just sticking with Array[Byte] for now, it covers most use cases, even base Java serialization, and avoids having to bring in another dependency like Kryo. 

We can follow up with another PR to create a more friendly API such as the writeTo or readFrom you are talking about.  Though for our purposes it is not necessary, as we are looking to read and write this to/from key value stores such as Redis or Cassandra.

**Comment by alexandrnikitin** [comment]
Closed via #14 
I just released 0.7.0 to Sonatype. It will be in Maven soon.

@velvia  I decided to go with `writeTo(OutputStream out)` and `readFrom(InputStream in)` approach because the intention is to support huge bloom filters. They won't fit into array of bytes :(
I hope you are OK with that.

**Comment by velvia** [comment]
Thanks, this is fine since we can always use ByteArrayOutputStream etc.
