### ISSUE TITLE
Opposite bloom filter wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [alexandrnikitin/bloom-filter-scala#8]
The opposite of a Bloom filter is a data structure that may report a false negative, but can never report a false positive.

It is handy for deduplication in realtime while unique values shouldn't be filtered out and possible non-filtered dublicates should be limited by some defined rate.

**Comment by alexandrnikitin** [comment]
I doubt that it's possible :blush: 

We use [Stable Bloom filter](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.85.1569&rep=rep1&type=pdf) for deduplication of streams. It works on infinite streams but introduces not only false positive error but false negative too.

**Comment by alexandrnikitin** [comment]
BTW, I have an intention to open the Stable Bloom filter here which will the only viable JVM implementation. I just need to find more time and motivation.

**Comment by plokhotnyuk** [comment]
Some ideas and basic implementation: https://github.com/jmhodges/opposite_of_a_bloom_filter

**Comment by alexandrnikitin** [comment]
Thank you for the link. I'm aware of such approach. But it has nothing to do with the Bloom filter data structure. It's not a probabilistic/ sketching data structure when you "sketch"/ "compress" an element to some number of bits. How it works: it has an array of elements (buffers in their case) where it stores last seen elements. It uses a hash code to decide where to store it.
